- platform: template
  sensors:
    family_home:
      value_template: >
        {% if states.input_boolean.away_mode.state == true %}
          false
        {% elif states.input_boolean.away_mode.state == false %}
          true
        {% endif %}
