- platform: template
  sensors:
    garage_door:
      value_template: >
        {% if states.cover.garage_door_opener.state in ['open','opening'] %}
          true
        {% elif states.cover.garage_door_opener.state in ['closed','closing'] %}
          false
        {% endif %}
    nursery_lights:
      value_template: >
        {% if states.light.ceiling_light.state == 'on' or states.light.led_light_strip.state == 'on' or states.switch.nightlight.state == 'on' %}
          true
        {% else %}
          false
        {% endif %}
